<?php

namespace Database\Seeders;

use App\Models\FeedReadyItem;
use Illuminate\Database\Seeder;

class FeedReadyItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'title' => 'Local Badminton Tournament Draws Record Participants',
                'summary' => 'The annual city badminton championship saw over 200 players from across the region compete this weekend.',
                'source' => 'Sports Daily',
                'url' => 'https://example.com/badminton-tournament',
                'published_at' => now()->subHours(2),
                'primary_category' => 'sports',
                'secondary_category' => 'badminton',
                'location_label' => 'Kuala Lumpur Sports Complex',
                'lat' => 3.1390,
                'lng' => 101.6869,
                'precision_type' => 'exact_area',
                'relevance_mode' => 'location_only',
                'is_active' => true,
            ],
            [
                'title' => 'New Badminton Academy Opens in Petaling Jaya',
                'summary' => 'A state-of-the-art badminton training facility has opened its doors, offering coaching for all skill levels.',
                'source' => 'Malay Mail',
                'url' => 'https://example.com/badminton-academy',
                'published_at' => now()->subHours(5),
                'primary_category' => 'sports',
                'secondary_category' => 'badminton',
                'location_label' => 'Petaling Jaya',
                'lat' => 3.1076,
                'lng' => 101.5932,
                'precision_type' => 'approximate_area',
                'relevance_mode' => 'hybrid',
                'is_active' => true,
            ],
            [
                'title' => 'National Badminton Team Announces Squad for Upcoming Championships',
                'summary' => 'The selection committee has named 12 players who will represent the nation in the upcoming Asian Championships.',
                'source' => 'Berita Nasional',
                'url' => 'https://example.com/national-badminton-squad',
                'published_at' => now()->subHours(8),
                'primary_category' => 'sports',
                'secondary_category' => 'badminton',
                'location_label' => 'Kuala Lumpur',
                'lat' => null,
                'lng' => null,
                'precision_type' => 'state_center',
                'relevance_mode' => 'category_only',
                'is_active' => true,
            ],
            [
                'title' => 'Condo Rental Prices Drop in Downtown Area',
                'summary' => 'Property market analysis shows a 5% decline in condominium rental rates across the city center.',
                'source' => 'Property Times',
                'url' => 'https://example.com/condo-rental-drop',
                'published_at' => now()->subHours(3),
                'primary_category' => 'property',
                'secondary_category' => 'rental',
                'location_label' => 'Bukit Bintang',
                'lat' => 3.1466,
                'lng' => 101.7103,
                'precision_type' => 'exact_area',
                'relevance_mode' => 'location_only',
                'is_active' => true,
            ],
            [
                'title' => 'Affordable Housing Project Announced for Subang Residents',
                'summary' => 'The government has unveiled plans for a new affordable housing development targeting young families in Subang.',
                'source' => 'Star Property',
                'url' => 'https://example.com/affordable-housing-subang',
                'published_at' => now()->subHours(6),
                'primary_category' => 'property',
                'secondary_category' => 'rental',
                'location_label' => 'Subang Jaya',
                'lat' => 3.0588,
                'lng' => 101.5858,
                'precision_type' => 'approximate_area',
                'relevance_mode' => 'hybrid',
                'is_active' => true,
            ],
            [
                'title' => 'National Property Index Shows Market Stabilization',
                'summary' => 'Latest data indicates the property market is showing signs of stabilization after months of fluctuation.',
                'source' => 'Edge Property',
                'url' => 'https://example.com/property-market-stable',
                'published_at' => now()->subHours(12),
                'primary_category' => 'property',
                'secondary_category' => 'rental',
                'location_label' => 'Malaysia',
                'lat' => null,
                'lng' => null,
                'precision_type' => 'country',
                'relevance_mode' => 'category_only',
                'is_active' => true,
            ],
            [
                'title' => 'Expressway Traffic Congestion Expected During Holiday Weekend',
                'summary' => 'Authorities warn of heavy traffic on major expressways as many plan their festive getaways.',
                'source' => 'Traffic Alert',
                'url' => 'https://example.com/expressway-congestion',
                'published_at' => now()->subHours(1),
                'primary_category' => 'transport',
                'secondary_category' => 'traffic',
                'location_label' => 'North-South Expressway',
                'lat' => 3.2565,
                'lng' => 101.5218,
                'precision_type' => 'exact_area',
                'relevance_mode' => 'location_only',
                'is_active' => true,
            ],
            [
                'title' => 'New MRT Line Extension to Open Next Month',
                'summary' => 'The much-anticipated MRT extension will begin operations, connecting more neighborhoods to the city center.',
                'source' => 'Urban Transport News',
                'url' => 'https://example.com/mrt-extension',
                'published_at' => now()->subHours(4),
                'primary_category' => 'transport',
                'secondary_category' => 'traffic',
                'location_label' => 'Klang Valley',
                'lat' => 3.0732,
                'lng' => 101.6042,
                'precision_type' => 'approximate_area',
                'relevance_mode' => 'hybrid',
                'is_active' => true,
            ],
            [
                'title' => 'KLIA Sees Record Passenger Traffic This Quarter',
                'summary' => 'Kuala Lumpur International Airport reports unprecedented passenger numbers driven by tourism recovery.',
                'source' => 'Aviation Weekly',
                'url' => 'https://example.com/klia-record-traffic',
                'published_at' => now()->subHours(10),
                'primary_category' => 'transport',
                'secondary_category' => 'traffic',
                'location_label' => 'Sepang',
                'lat' => 2.7456,
                'lng' => 101.7099,
                'precision_type' => 'exact_area',
                'relevance_mode' => 'location_only',
                'is_active' => true,
            ],
            [
                'title' => 'Badminton Court Booking App Launches Nationwide',
                'summary' => 'A new mobile app allows players to book badminton courts instantly across participating venues.',
                'source' => 'Tech Sports',
                'url' => 'https://example.com/badminton-booking-app',
                'published_at' => now()->subHours(7),
                'primary_category' => 'sports',
                'secondary_category' => 'badminton',
                'location_label' => 'National',
                'lat' => null,
                'lng' => null,
                'precision_type' => 'national',
                'relevance_mode' => 'category_only',
                'is_active' => true,
            ],
            [
                'title' => 'Serviced Apartment Rentals on the Rise in Mont Kiara',
                'summary' => 'Demand for serviced apartments in Mont Kiara continues to grow due to expatriates and digital nomads.',
                'source' => 'Home Finder',
                'url' => 'https://example.com/serviced-apartments',
                'published_at' => now()->subHours(9),
                'primary_category' => 'property',
                'secondary_category' => 'rental',
                'location_label' => 'Mont Kiara',
                'lat' => 3.1618,
                'lng' => 101.6662,
                'precision_type' => 'exact_area',
                'relevance_mode' => 'location_only',
                'is_active' => true,
            ],
            [
                'title' => 'Traffic Advisory: Road Closures in Shah Alam This Weekend',
                'summary' => 'Motorists advised to avoid certain roads in Shah Alam as maintenance work will cause temporary closures.',
                'source' => 'Selangor Traffic',
                'url' => 'https://example.com/shah-alam-road-closure',
                'published_at' => now()->subHours(11),
                'primary_category' => 'transport',
                'secondary_category' => 'traffic',
                'location_label' => 'Shah Alam',
                'lat' => 3.0738,
                'lng' => 101.5183,
                'precision_type' => 'approximate_area',
                'relevance_mode' => 'hybrid',
                'is_active' => true,
            ],
            [
                'title' => 'Youth Badminton Championship Kicks Off in Johor',
                'summary' => 'Young talents from southern region compete in the annual youth badminton championship.',
                'source' => 'Southern Sports',
                'url' => 'https://example.com/youth-badminton-johor',
                'published_at' => now()->subHours(14),
                'primary_category' => 'sports',
                'secondary_category' => 'badminton',
                'location_label' => 'Johor Bahru',
                'lat' => 1.4927,
                'lng' => 103.7414,
                'precision_type' => 'exact_area',
                'relevance_mode' => 'location_only',
                'is_active' => true,
            ],
            [
                'title' => 'Penang Property Investment Forum Draws International Buyers',
                'summary' => 'The annual property investment forum in Penang attracts investors from Singapore, Hong Kong, and Taiwan.',
                'source' => 'Invest Property',
                'url' => 'https://example.com/penang-property-forum',
                'published_at' => now()->subHours(16),
                'primary_category' => 'property',
                'secondary_category' => 'rental',
                'location_label' => 'George Town',
                'lat' => 5.4141,
                'lng' => 100.3288,
                'precision_type' => 'exact_area',
                'relevance_mode' => 'location_only',
                'is_active' => true,
            ],
            [
                'title' => 'LRT3 Project Progress Update: 85% Complete',
                'summary' => 'The Light Rail Transit 3 project is on track for completion, promising better connectivity for Klang residents.',
                'source' => 'Railway Gazette',
                'url' => 'https://example.com/lrt3-progress',
                'published_at' => now()->subHours(20),
                'primary_category' => 'transport',
                'secondary_category' => 'traffic',
                'location_label' => 'Klang',
                'lat' => 3.0480,
                'lng' => 101.4433,
                'precision_type' => 'approximate_area',
                'relevance_mode' => 'hybrid',
                'is_active' => true,
            ],
            [
                'title' => 'Indoor Stadium Badminton League Results',
                'summary' => 'Results from the weekend matches in the indoor stadium badminton league competition.',
                'source' => 'Stadium Sports',
                'url' => 'https://example.com/indoor-badminton-league',
                'published_at' => now()->subHours(22),
                'primary_category' => 'sports',
                'secondary_category' => 'badminton',
                'location_label' => 'Mid Valley',
                'lat' => 3.1189,
                'lng' => 101.6768,
                'precision_type' => 'exact_area',
                'relevance_mode' => 'location_only',
                'is_active' => true,
            ],
        ];

        foreach ($items as $item) {
            FeedReadyItem::updateOrCreate(
                ['url' => $item['url']],
                $item
            );
        }
    }
}
