<?php

namespace App\Http\Controllers;

use App\Models\FeedReadyItem;
use App\Models\NewsItem;
use App\Models\LocationAlias;
use App\Services\FeedQuery;
use App\Support\Slug;
use App\Support\Loc;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

/**
 * Sitemaps, robots and llms.txt.
 *
 * Generated rather than written by hand: places and categories change as the
 * pipeline learns new ones, and a sitemap that has to be regenerated by a person
 * is a sitemap that goes stale.
 *
 * llms.txt is the same idea aimed at answer engines - a plain statement of what
 * this site holds and where the useful entry points are, so a model summarising
 * "local news in Shah Alam" has something better to work from than scraped
 * navigation.
 */
class SitemapController extends Controller
{
    public function __construct(private FeedQuery $feed)
    {
    }

    /** Sitemap index. */
    public function index(): Response
    {
        $maps = ['sitemap-core.xml', 'sitemap-stories.xml', 'sitemap-places.xml', 'sitemap-topics.xml'];
        $now  = now()->toAtomString();

        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
             . '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

        foreach ($maps as $map) {
            $xml .= "  <sitemap><loc>" . e(url($map)) . "</loc><lastmod>{$now}</lastmod></sitemap>\n";
        }

        $xml .= '</sitemapindex>';

        return $this->xml($xml);
    }

    public function core(): Response
    {
        $urls = [
            [url('/'), 'hourly', '1.0'],
            [route('interest'), 'hourly', '0.9'],
            [route('marketplace'), 'monthly', '0.3'],
            [route('legal', ['page' => 'terms']), 'yearly', '0.2'],
            [route('legal', ['page' => 'privacy']), 'yearly', '0.2'],
            [route('legal', ['page' => 'disclaimer']), 'yearly', '0.2'],
        ];

        return $this->xml($this->urlSet($urls));
    }

    /**
     * The stories themselves.
     *
     * They were missing entirely: the only route to a story page was a crawler
     * following a headline out of a feed that changes hourly, so anything that
     * scrolled off the front page before Google came back was never listed
     * anywhere. Every headline still links here - that has not changed and is
     * what carries the weight - but a sitemap is how the ones no longer on a
     * feed page get found at all.
     *
     * Newest first, capped well under the 50,000 a sitemap may hold, and only
     * pages that actually resolve: active, not discarded, not a duplicate of
     * another story.
     */
    /**
     * The Google News sitemap: qualifying breaking community reports (and
     * nothing older than two days, per the News guidelines). Entries fall out
     * of the window on their own; the story page stays.
     */
    public function news(): Response
    {
        $rows = DB::table('community_post_meta as m')->join('news_items as n', 'n.id', '=', 'm.news_item_id')
            ->where('m.seo_eligibility', 'news')->where('m.trust_status', '<>', 'removed')
            ->where('n.status', 'active')->where('n.published_at', '>=', now()->subHours(48))
            ->orderByDesc('n.published_at')->limit(1000)->get(['n.id', 'n.title', 'n.published_at', 'n.source_language']);

        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
            . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">' . "\n";

        foreach ($rows as $r) {
            $lang = in_array($r->source_language, ['en', 'ms', 'zh'], true) ? $r->source_language : 'en';
            $xml .= "  <url>\n    <loc>" . htmlspecialchars(route('post.show', ['id' => $r->id]), ENT_XML1) . "</loc>\n"
                . "    <news:news>\n      <news:publication>\n        <news:name>Nearbypost</news:name>\n        <news:language>{$lang}</news:language>\n      </news:publication>\n"
                . "      <news:publication_date>" . \Carbon\Carbon::parse($r->published_at)->toAtomString() . "</news:publication_date>\n"
                . "      <news:title>" . htmlspecialchars((string) $r->title, ENT_XML1) . "</news:title>\n    </news:news>\n  </url>\n";
        }

        return response($xml . '</urlset>', 200, ['Content-Type' => 'application/xml; charset=UTF-8']);
    }

    public function stories(): Response
    {
        $stories = NewsItem::query()
            ->where('status', 'active')
            ->where('discarded', false)
            ->whereNull('duplicate_of')
            ->where('ai_status', 'success')
            ->whereNotNull('published_at')
            ->orderByDesc('published_at')
            ->limit(20000)
            ->get(['id', 'published_at', 'updated_at']);

        $urls = [];

        foreach ($stories as $story) {
            $age = $story->published_at?->diffInDays(now()) ?? 999;

            $urls[] = [
                Loc::route('story', ['id' => $story->id]),
                // A news story is rewritten in its first day and then stands.
                $age < 2 ? 'hourly' : ($age < 14 ? 'daily' : 'monthly'),
                $age < 2 ? '0.9' : ($age < 14 ? '0.6' : '0.3'),
                ($story->updated_at ?? $story->published_at)->toAtomString(),
            ];
        }

        return $this->xml($this->urlSet($urls));
    }

    /** Every location that has a landing page. */
    public function places(): Response
    {
        $places = LocationAlias::query()
            ->where('is_active', true)
            ->pluck('canonical_name')
            ->unique();

        $urls = [];

        foreach ($places as $place) {
            // ⛔ A name with no Latin letters slugs to '' and route()
            // throws - which does not lose one URL, it loses the SITEMAP.
            $placeSlug = Slug::make($place);

            if ($placeSlug === '') {
                continue;
            }

            $urls[] = [route('place', ['slug' => $placeSlug]), 'hourly', '0.8'];
        }

        return $this->xml($this->urlSet($urls));
    }

    /** Categories, and the place-and-category long tail. */
    public function topics(): Response
    {
        $categories = $this->feed->categories();
        $urls = [];

        foreach ($categories as $category) {
            $urls[] = [route('category', ['slug' => Slug::make($category)]), 'hourly', '0.8'];
        }

        // Only the places that actually carry stories get combination URLs.
        // Listing every place against every category would publish thousands of
        // pages that resolve to nothing, which is worse than not listing them.
        $activePlaces = FeedReadyItem::query()
            ->where('is_active', true)
            ->whereNotNull('location_label')
            ->where('published_at', '>=', now()->subDays(30))
            ->distinct()
            ->pluck('location_label')
            ->filter()
            ->take(60);

        foreach ($activePlaces as $place) {
            foreach ($categories as $category) {
                $urls[] = [
                    route('place.category', [
                        'slug'         => Slug::make($place),
                        'categorySlug' => Slug::make($category),
                    ]),
                    'daily',
                    '0.5',
                ];
            }
        }

        return $this->xml($this->urlSet($urls));
    }

    public function robots(): Response
    {
        $lines = [
            'User-agent: *',
            'Allow: /',
            'Disallow: /admin',
            'Disallow: /api/',
            '',
            '# Answer engines: see ' . url('llms.txt'),
            '',
            'Sitemap: ' . url('sitemap.xml'),
        ];

        return response(implode("\n", $lines) . "\n", 200)
            ->header('Content-Type', 'text/plain; charset=utf-8');
    }

    /** A plain-language description of the site for answer engines. */
    public function llms(): Response
    {
        $categories = $this->feed->categories();
        $name       = config('app.name');

        $body = "# {$name}\n\n"
            . "> Local and hyperlocal news for Malaysia, organised by place and topic. "
            . "Headlines and short summaries are gathered from Malaysian news publishers and "
            . "placed on a map by the town or area each story concerns.\n\n"
            . "## What this site is\n\n"
            . "- Coverage: Malaysia, all states and federal territories\n"
            . "- Languages: English and Malay sources\n"
            . "- Updated: continuously, several times an hour\n"
            . "- Every headline links to the original publisher; full articles are not republished\n"
            . "- Locations are approximate: a story is placed near the town or area it mentions\n\n"
            . "## Entry points\n\n"
            . "- " . url('/') . " - news near a chosen place\n"
            . "- " . route('interest') . " - latest news across Malaysia\n"
            . "- " . url('news/{place}') . " - news for one town or city, e.g. " . route('place', ['slug' => 'shah-alam']) . "\n"
            . "- " . url('category/{topic}') . " - one topic across Malaysia\n"
            . "- " . url('news/{place}/{topic}') . " - one topic in one place\n\n"
            . "## Topics\n\n";

        foreach ($categories as $category) {
            $body .= '- ' . ucwords($category) . ': ' . route('category', ['slug' => Slug::make($category)]) . "\n";
        }

        $body .= "\n## Machine-readable\n\n"
            . '- Sitemap: ' . url('sitemap.xml') . "\n"
            . "- Every page carries schema.org JSON-LD (ItemList of NewsArticle, with contentLocation)\n";

        return response($body, 200)->header('Content-Type', 'text/plain; charset=utf-8');
    }

    // ── helpers ─────────────────────────────────────────────────────────

    private function urlSet(array $urls): string
    {
        $now = now()->toAtomString();

        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
             . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

        foreach ($urls as $url) {
            [$loc, $freq, $priority] = $url;

            // A story's lastmod is when it was published, not when the sitemap
            // was generated. Telling a crawler that four thousand pages all
            // changed this minute, every time it asks, teaches it that lastmod
            // here means nothing - and then it stops using it to decide what is
            // worth re-fetching.
            $lastmod = $url[3] ?? $now;

            $xml .= '  <url><loc>' . e($loc) . '</loc>'
                 . "<lastmod>{$lastmod}</lastmod>"
                 . "<changefreq>{$freq}</changefreq>"
                 . "<priority>{$priority}</priority></url>\n";
        }

        return $xml . '</urlset>';
    }

    private function xml(string $body): Response
    {
        return response($body, 200)->header('Content-Type', 'application/xml; charset=utf-8');
    }
}
