<?php

namespace App\Http\Controllers;

use App\Models\FeedReadyItem;
use App\Models\LocationAlias;
use App\Services\FeedQuery;
use App\Support\Slug;
use Illuminate\Http\Response;

/**
 * Sitemaps, robots and llms.txt.
 *
 * Generated rather than written by hand: places and categories change as the
 * pipeline learns new ones, and a sitemap that has to be regenerated by a person
 * is a sitemap that goes stale.
 *
 * llms.txt is the same idea aimed at answer engines - a plain statement of what
 * this site holds and where the useful entry points are, so a model summarising
 * "local news in Shah Alam" has something better to work from than scraped
 * navigation.
 */
class SitemapController extends Controller
{
    public function __construct(private FeedQuery $feed)
    {
    }

    /** Sitemap index. */
    public function index(): Response
    {
        $maps = ['sitemap-core.xml', 'sitemap-places.xml', 'sitemap-topics.xml'];
        $now  = now()->toAtomString();

        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
             . '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

        foreach ($maps as $map) {
            $xml .= "  <sitemap><loc>" . e(url($map)) . "</loc><lastmod>{$now}</lastmod></sitemap>\n";
        }

        $xml .= '</sitemapindex>';

        return $this->xml($xml);
    }

    public function core(): Response
    {
        $urls = [
            [url('/'), 'hourly', '1.0'],
            [route('interest'), 'hourly', '0.9'],
            [route('marketplace'), 'monthly', '0.3'],
            [route('legal', ['page' => 'terms']), 'yearly', '0.2'],
            [route('legal', ['page' => 'privacy']), 'yearly', '0.2'],
            [route('legal', ['page' => 'disclaimer']), 'yearly', '0.2'],
        ];

        return $this->xml($this->urlSet($urls));
    }

    /** Every location that has a landing page. */
    public function places(): Response
    {
        $places = LocationAlias::query()
            ->where('is_active', true)
            ->pluck('canonical_name')
            ->unique();

        $urls = [];

        foreach ($places as $place) {
            $urls[] = [route('place', ['slug' => Slug::make($place)]), 'hourly', '0.8'];
        }

        return $this->xml($this->urlSet($urls));
    }

    /** Categories, and the place-and-category long tail. */
    public function topics(): Response
    {
        $categories = $this->feed->categories();
        $urls = [];

        foreach ($categories as $category) {
            $urls[] = [route('category', ['slug' => Slug::make($category)]), 'hourly', '0.8'];
        }

        // Only the places that actually carry stories get combination URLs.
        // Listing every place against every category would publish thousands of
        // pages that resolve to nothing, which is worse than not listing them.
        $activePlaces = FeedReadyItem::query()
            ->where('is_active', true)
            ->whereNotNull('location_label')
            ->where('published_at', '>=', now()->subDays(30))
            ->distinct()
            ->pluck('location_label')
            ->filter()
            ->take(60);

        foreach ($activePlaces as $place) {
            foreach ($categories as $category) {
                $urls[] = [
                    route('place.category', [
                        'slug'         => Slug::make($place),
                        'categorySlug' => Slug::make($category),
                    ]),
                    'daily',
                    '0.5',
                ];
            }
        }

        return $this->xml($this->urlSet($urls));
    }

    public function robots(): Response
    {
        $lines = [
            'User-agent: *',
            'Allow: /',
            'Disallow: /admin',
            'Disallow: /api/',
            '',
            '# Answer engines: see ' . url('llms.txt'),
            '',
            'Sitemap: ' . url('sitemap.xml'),
        ];

        return response(implode("\n", $lines) . "\n", 200)
            ->header('Content-Type', 'text/plain; charset=utf-8');
    }

    /** A plain-language description of the site for answer engines. */
    public function llms(): Response
    {
        $categories = $this->feed->categories();
        $name       = config('app.name');

        $body = "# {$name}\n\n"
            . "> Local and hyperlocal news for Malaysia, organised by place and topic. "
            . "Headlines and short summaries are gathered from Malaysian news publishers and "
            . "placed on a map by the town or area each story concerns.\n\n"
            . "## What this site is\n\n"
            . "- Coverage: Malaysia, all states and federal territories\n"
            . "- Languages: English and Malay sources\n"
            . "- Updated: continuously, several times an hour\n"
            . "- Every headline links to the original publisher; full articles are not republished\n"
            . "- Locations are approximate: a story is placed near the town or area it mentions\n\n"
            . "## Entry points\n\n"
            . "- " . url('/') . " - news near a chosen place\n"
            . "- " . route('interest') . " - latest news across Malaysia\n"
            . "- " . url('news/{place}') . " - news for one town or city, e.g. " . route('place', ['slug' => 'shah-alam']) . "\n"
            . "- " . url('category/{topic}') . " - one topic across Malaysia\n"
            . "- " . url('news/{place}/{topic}') . " - one topic in one place\n\n"
            . "## Topics\n\n";

        foreach ($categories as $category) {
            $body .= '- ' . ucwords($category) . ': ' . route('category', ['slug' => Slug::make($category)]) . "\n";
        }

        $body .= "\n## Machine-readable\n\n"
            . '- Sitemap: ' . url('sitemap.xml') . "\n"
            . "- Every page carries schema.org JSON-LD (ItemList of NewsArticle, with contentLocation)\n";

        return response($body, 200)->header('Content-Type', 'text/plain; charset=utf-8');
    }

    // ── helpers ─────────────────────────────────────────────────────────

    private function urlSet(array $urls): string
    {
        $now = now()->toAtomString();

        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
             . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

        foreach ($urls as [$loc, $freq, $priority]) {
            $xml .= '  <url><loc>' . e($loc) . '</loc>'
                 . "<lastmod>{$now}</lastmod>"
                 . "<changefreq>{$freq}</changefreq>"
                 . "<priority>{$priority}</priority></url>\n";
        }

        return $xml . '</urlset>';
    }

    private function xml(string $body): Response
    {
        return response($body, 200)->header('Content-Type', 'application/xml; charset=utf-8');
    }
}
